spring.application.name=quickshop

server.port=8090
#################################################
# ROUTES
#################################################

spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.server.webflux.routes[1].id=inventory-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/inventory/**

#################################################
# ACTUATOR
#################################################

management.endpoints.web.exposure.include=*

###################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8091/realms/quickshop-realm
spring.main.web-application-type=reactive

#####################################################
logging.level.root=INFO
logging.level.com.quickshop=DEBUG
logging.file.name=logs/gateway.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{X-Correlation-Id}] %-5level %logger{36} - %msg%n



